services:
  - type: web
    name: ai-diary
    env: node
    region: singapore
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: DIRECT_URL
        sync: false
      - key: AUTH_SECRET
        sync: false
      - key: AUTH_GOOGLE_ID
        sync: false
      - key: AUTH_GOOGLE_SECRET
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: NEXTAUTH_URL
        sync: false
